INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'madhu@gmail.com', 'madhu', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'malikarjun@gmail.com', 'malikarjun', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'kothi@gmail.com', 'kothi', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'ambika@gmail.com', 'ambika', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'preetam@gmail.com', 'preetam', 'ADMIN');